#version 450

layout (local_size_x = 16, local_size_y = 16) in;

layout (set = 0, binding = 0, r16f) uniform readonly image3D raid;
layout (set = 1, binding = 0, r16f) uniform image2D trade;

void main() {
    float color = 0.0;
    for (int z = 0; z < 64; z += 1) {
        color += imageLoad(raid, ivec3(gl_GlobalInvocationID.xy, z)).r;
    }
    color *= 0.015625;
    imageStore(trade, ivec2(gl_GlobalInvocationID.xy), vec4(color));
}